name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          repositories: |
            [{
              "id":"visionapi",
              "name":"vision-api",
              "username": "flonix8", 
              "password": "${{ secrets.VISION_API_READ_TOKEN }}", 
              "url":"https://maven.pkg.github.com/starwit/vision-api",
              "snapshots":{"enabled":true}
            }]
      - name: Build with Maven
        working-directory: java
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}