name: Create Python Release

on:
  workflow_dispatch:
    inputs:
      versionChoice:
        type: choice
        required: true
        description: Version Change
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  create-release:
    name: create new python release
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
      - name: Create new version in pyproject.toml
        run: poetry version $VERSION
        working-directory: python
        env:
          VERSION: ${{ inputs.versionChoice }}
      - name: Commit new version
        run: |
          git config --global user.email "code@starwit.de"
          git config --global user.name "Starwit"
          git remote set-url --push origin https://Starwit:$GITHUB_TOKEN@github.com/starwit/vision-lib.git
          git add python/pyproject.toml
          modifications=$(git status | grep "modified" || true)
          if [ ! -z "$modifications" ]; then
            echo "modifications found: $modifications"
            git commit -m "modified project version" python/pyproject.toml
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        run: |
          APP_VERSION=$(grep "^version" python/pyproject.toml | head -1 | cut -d'"' -f2)
          gh release create "$APP_VERSION" --title "$APP_VERSION" --target "$(git branch --show-current)" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
