name: PR Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: "Build and run docker image"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: checkout
      uses: actions/checkout@v4

    - name: build docker
      run: |
        docker build -t docker.internal.starwit-infra.de/movement-predictor:tmp .

  cleanup:
    name: "Clean docker"
    needs: build 
    runs-on: [self-hosted, linux, X64]
    if: always()

    steps:
      - name: docker cleanup
        run: |
          docker buildx prune -af
          docker rmi docker.internal.starwit-infra.de/movement-predictor:tmp
