name: PR Build

# PR build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  packages: read
  contents: read

# just runs Maven, NPM and Docker build
jobs:
  build:
    name: "Install software"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2        

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - run: mvn --version

    - name: Build with Maven
      run: mvn clean -B package --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



